apiVersion: v1
kind: Service
metadata:
  name: seat-management-svc
  labels:
    app: seatbooking-app
    name: seat-management-svc
spec:
  selector:
    app: seatbooking-app
    name: seatbooking-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seat-management-svc
  labels:
    app: seatbooking-app
    name: seat-management-svc
spec:
  selector:
    matchLabels:
      app: seatbooking-app
      name: seatbooking-pod
  #replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: seatbooking-pod
      labels:
        app: seatbooking-app
        name: seatbooking-pod
    spec:
      containers:
        - name: seatbooking-container
          image: dhamodaran/seatbooking_api:latest
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 4000
          env:
            - name: CHECK_DB
              value: enabled
            - name: DB_HOST
              value: 192.168.65.2
            - name: NODE_ENV
              value: production
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: sbasecrets
                  key: sba_db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sbasecrets
                  key: sba_db_password
            - name: DB_SCHEME
              valueFrom:
                secretKeyRef:
                  name: sbasecrets
                  key: sba_db_schema
            - name: INFRA_DB_USER
              valueFrom:
                secretKeyRef:
                  name: sbasecrets
                  key: infra_db_user
            - name: INFRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sbasecrets
                  key: infra_db_password
