# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Development CI

on:
  push:
    branches: ["feature*"]
  pull_request:
    branches: ["main"]
    types: ["opened", "edited", "reopened"]
jobs:
  dep_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: h4sh5/npm-mal-feed-check@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Set current date as env variable
        run: echo "BUILD_TS=$(date +'%Y%m%dT%H:%M:%S.%s')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $BUILD_TS # Gives "2022-12-11T01:42:20"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Output Run Id
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}
      - run: npm ci
      - run: npm run lint
  #trigger_workflow:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: verify
  #      run: |
  #        curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/NeoWebArchSeatBooking/KIaC/actions/workflows/sb_api.yml/dispatches --data '{"ref": "main"}'
