name: Publish the Stage
on:
  pull_request:
    branches: ["stage"]
    types: ["closed"]
env:
  IMG_NAME: seatbooking_api
jobs:
  trigger_cd:
    runs-on: ubuntu-latest
    #needs: ['build_docker']
    steps:
      - name: Trigger Workflow
        run: |
          curl -XPOST -u "sgddaran:${{secrets.GITHUB_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/neowebarchseatbooking/kiac/actions/workflows/sb_api.yml/dispatches --data '{"inputs": {"tags":"image"},"ref":"main"}'

          
