name: Publish the Stage
on:
  pull_request:
    branches: ["stage"]
    types: ["closed"]
env:
  IMG_NAME: seatbooking_api
jobs:
  trigger_cd:
    runs-on: ubuntu-latest
    #needs: ['build_docker']
    steps:
      - name: Trigger Workflow
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'KIaC',
              workflow_id: 'sb_api.yml',
              ref: 'main',
              inputs: {
                "tags": "test"
              }
            })
